version: '3.8'

services:
  nodejs_mongo_docker:
    image: nodejs_mongo_docker
    build: .
    environment: 
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db